# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

